### ISSUE TITLE
essentials.itemlore.<effect> not listed

### ISSUE THREAD

**Issue by chrisraj1** [Xeyame/essinfo.xeya.me#21]
essentials.itemlore.<effect> is not listed even though it exists. I know this because I gave the permission essentials.itemlore.* and it allowed me to use color codes in my lore. Not sure if essentials.itemlore.prevent-type.<material_name> is also a permission that needs to defined, but I would assume so as itemname also has that node.

essntials.itemlore is already in the library, I am only referring to essentials.itemlore.<effect> and possibly essentials.itemlore.prevent-type.<material_name> if it exists.

Both essentials.itemlore and essentials.itemname stop autofill within LP at those points. I sort of had to guess with essentials.itemlore.*

**Comment by Xeyame** [comment]
I can't find anything about essentials.itemlore.prevent-type.<material_name> in the itemlore command. For itemname i can find it in [here](https://github.com/EssentialsX/Essentials/blob/2.x/Essentials/src/main/java/com/earth2me/essentials/commands/Commanditemname.java#L18). essentials.itemname.prevent-type might not get autofiled in LP because it isn't defined in plugin.yml (not too sure about that tho)

Please reply to this issue if `essentials.itemlore.prevent-type.<material_name>` acutally exist and it will be added :)
